on:
  push:
    branches: [ main ]
jobs:
  pester-test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: 'Run Pester Tests'
        shell: pwsh
        run: |
          function pactl {}
          Invoke-Pester ./PoshPulseAudio.Test.ps1
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install PSScriptAnalyzer'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
      - name: 'Run PSScriptAnalyzer'
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path *.ps1 -Recurse -Outvariable issues
          $errors = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }